version: 2.7.{build}

image: Visual Studio 2017

configuration: Debug

init:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
- '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat"'
- ps: |
    $vsixPath = "$($env:USERPROFILE)\sqlite-uwp-3180000.vsix"
    (New-Object Net.WebClient).DownloadFile('https://visualstudiogallery.msdn.microsoft.com/4913e7d5-96c9-4dde-a1a1-69820d615936/file/161586/16/sqlite-uwp-3180000.vsix', $vsixPath)
    "`"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\VSIXInstaller.exe`" /q /a $vsixPath" | out-file ".\install-vsix.cmd" -Encoding ASCII
    & .\install-vsix.cmd
    
before_build:
- msbuild src\MoneyFox.sln /t:restore
    
build:
  verbosity: minimal
  
environment:
  JavaSdkDirectory: C:\Program Files (x86)\Java\jdk1.8.0